### ISSUE TITLE
[Question] Is there any way we could use this and uglify the generated bundles?

### ISSUE THREAD

**Issue by alterx** [goto-bus-stop/split-require#11]
I'm new to Browserify and trying to use this to code split some routes. So far everything works as expected (I'm using the `package.json` scripts)

```
"scripts": {
    ...
    "build:js": "NODE_ENV=production browserify index.js -p [ split-require --dir static/ --public static/ ] | uglifyjs -c > static/bundle.js",
    "build": "npm run build:css && npm run build:js",
    ...
  },
```

There's only one thing I noticed: the generated bundles aren't `uglified` (of course, I'm just uglifying the result of `browserify index.js`). 

Is there a way to uglify the results of this plugin?

**Comment by goto-bus-stop** [comment]
hey, it's possible to do this through the Node API but not the CLI.

With the Node API, you can listen for the `split.pipeline` event on the browserify instance, and add a minifier to that pipeline. [minify-stream](https://npmjs.com/package/minify-stream) is a module you can use that wraps uglify in a Node stream interface:

```js
var minify = require('minify-stream')

var b = browserify(...)
b.plugin(splitRequire, { ... })
b.on('split.pipeline', function (pipeline) {
  pipeline.get('wrap').push(minify({
    /* options to uglify-es */
  }))
})
```

we could make this possible through the CLI, perhaps, using something like [outpipe](https://npmjs.com/package/outpipe). outpipe only works for a single file, but it might be possible to somehow make it work with a syntax like `[ split-require -o "uglifyjs > ./static/%f" ]` and replace `%f` with the filename.

**Comment by alterx** [comment]
Hey, thanks for the quick response, I ended up doing something similar: 
https://github.com/alterx/choo-browserify-beaker-starter/blob/master/scripts/build.js#L15
:D
